version: "3.9"

services:
  frontend:
    container_name: app
    image: app
    restart: always
    build:
      tags:
        - "mitchellmudd.azurecr.io/samples/vitereact:latest"
      context: ./client
      dockerfile: Dockerfile
      target: base
      platforms:
        - "linux/amd64"
    ports:
      - "5173:5173"
  backend:
    container_name: api
    image: api
    restart: always
    build:
      tags:
        - "mitchellmudd.azurecr.io/samples/expressapi:latest"
      context: ./server
      dockerfile: Dockerfile
      target: base
      platforms:
        - "linux/amd64"
    ports:
      - "8080:8080"
