name: Deploy Docker images to Azure Container Registry
run-name: Deploy Docker images to Azure Container Registry ${{github.actor}} ${{ github.run_number }}
on: [push]
jobs:
    build-docker-containers:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Login to Azure Container Registry
              uses: azure/docker-login@v1
              with:
                  login-server: ${{ secrets.REGISTRY_NAME }}.azurecr.io
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}
            - name: Build and push
              uses: azure/docker-build-push@v1
              with:
                  image: ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:${{ github.run_number }}
                  file: ./Dockerfile
                  tags: ${{ github.run_number }}